### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by jaels**

### CODE REVIEW

**Comment by msachi** [comment]
Hey @jaels, you could format the kata example into a proper sentence, and your markdown notation of the code didn't work well (note that you can use javascript notation) - but otherwise looks good!

**Comment by jaels** [comment]
OK, thanks! feel free to improve it! (I'm in the stages of learning this whole thing properly)
what do you mean by format the kata example into a proper sentence? and by javascript notaion?

**Comment by jaels** [comment]
And another question - who is in charge of merging it?

**Comment by msachi** [comment]
Hey, I've made the edits, it will be easiest for you to see what I mean in this way. Feel free to change anything back if you prefer.
What I mean by javascript notation is that it's possible to highlight the syntax correctly by typing 'javascript' after your three back-ticks. Check my edits to see what this looks like.

**Comment by msachi** [comment]
And no one is really in charge, whoever takes the time to read and comment on your work usually also then merges it. So in this case I'm happy to do it : )

**Comment by jaels** [comment]
OK, I get you now, looks good. thanks!
yeah go for it!!!

**Comment by msachi** [comment]
Welcome, thanks for your TIL!

**Pull request merged**
