### PR TITLE
Adding two TILs

### PR DESCRIPTION
**Pull request by msachi**
Adding two TILs: swapping variable values and for loop condition expression

### CODE REVIEW

**Comment by msachi** [comment]
Another TIL added on repeating characters

**Comment by bradreeder** [comment]
Hey msachi! Looks great. On the latter TIL you might also consider adding a reference to the ES6 method Array.fill() : https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

Are you using a destructuring assignment in the first TIL? Don't need to add any detail but wonder if it would be worth adding a hyperlink to a MDN article or something similar, so people can follow-up if they want to. I'm happy to merge if you prefer it as it is.

**Comment by msachi** [comment]
Great, thanks a lot! I've edited both files based on your suggestions - let me know if this is the use of the fill method that you had in mind.

**Comment by bradreeder** [comment]
That was what I was thinking, sure. :)

Merged, nice work!

**Comment by msachi** [comment]
Sweet!

**Pull request merged**
