### PR TITLE
added new t-i-l on functional classes

### PR DESCRIPTION
**Pull request by alwinsol**

### CODE REVIEW

**Comment by lucymonie** [comment]
Hey @alwinsol, I read this, and I must say I don't understand functional classes. I didn't find that I could understand them after reading your TIL, though I don't doubt that you get it! I'm just wondering whether it needs a little more unpicking and teasing out to make it clearer to the uninitiated? However, it could just be me! So I will wait for @msachi to comment.

**Comment by msachi** [comment]
Hi both, I agree with @lucymonie, it wasn't very clear to me either. Perhaps you could elaborate a little, and use some examples?

**Comment by alwinruby** [comment]
Thank you guys, I've just revisited my notes and realise this is part of a bigger piece so I will go back and rewrite it out.

**Comment by alwinsol** [comment]
I will close this pull request and raise another

**Pull request closed without merging**
