### PR TITLE
Added JavaScriptClasses t-i-l

### PR DESCRIPTION
**Pull request by alwinsol**
Re done and expanded the t-il

### CODE REVIEW

**Comment by lucymonie** [comment]
Hey @alwinsol, I think this is much clearer. Three suggestions:
1. First paragraph, suggested edit:
   
   > If you want to create multiple objects with similar methods and properties in JavaScript, the best options are functional classes, or constructor function. There are four styles of functional classes.
2. The word 'be' is missing from the following paragraph:
   
   > Take for example, a street, which has many houses. Every house on the street requires a colour for the house, a front door with methods to open and close the door. A very simple example of where houses may **be** thought of as objects.
3. At 147 lines, perhaps this is a tutorial? Or perhaps it could be split into four TILs?

**Comment by alwinsol** [comment]
Thanks @lucymonie, I have incorporated the first two suggestions.  I see what you mean about the third, however I think its clearer to have all of them together in one place rather than going elsewhere.

**Comment by lucymonie** [comment]
Sure thing. @msachi - your thoughts?

**Comment by msachi** [comment]
Hi both! This is much clearer indeed and I like examples! I've taken the liberty to make some minor edits - feel free to change back if you don't like any.

Other than that I was confused by the code on two occasions:
- is `houseMethods.open` meant to be `houseMethods.openDoor` (and the same for the close method)?
- the function is defined as `house` but then you use `var house = House('red')` - isn't this calling function `House` (that doesn't exist) rather than `house` (that does)?

I might just be missing something but do double check...

**Comment by SavageWilliam** [comment]
@alwinsol A nice informative self contained file, I like how you've clearly broken it down! Not a major comment, but how about a small heading for the beginning of each style? Just for the readers ease of jumping between them.
I agree with @lucymonie, perhaps with added references this would be suitable as a tutorial? It does stray a little from the TIL guidelines.

**Comment by alwinsol** [comment]
Thank you very much @msachi, yes you were right and I have updated accordingly.  OK @lucymonie and @SavageWilliam, I think in order for this to be a tutorial, it should go a bit further with more examples and be fleshed out further.  I feel that the way it is, it's a long today-i-learned, due to the four styles which do the same thing.  Would it be better if someone had to open four separate today I learned, which in essence do the same thing or is as I feel, one which is slightly longer?  When I started writing this up it was to sum up part of what I'd learned on the Udacity Object Oriented JavaScript Course.

**Comment by msachi** [comment]
I suppose it's in a format that's something in between a README and a TIL. The way I understand it originally TILs were meant for quick tips that you would learn e.g. when solving a kata, and would then write up in 10 minutes. That's something we could discuss on gitter, if we want another repo for longer documents that are not READMEs, or we just allow various formats of TILs...

**Comment by lucymonie** [comment]
I agree @alwinsol that it makes more sense for it to be a long TIL or a tutorial than four separate items that would really need to be read together to make sense. I think I would probably err or the side of adding more and making it a tutorial because it is a big subject and a really helpful one. In the case of longer TILs, the contribution guidelines suggest narrowing the scope, splitting it up into multiple TILs, or writing a blog post on the subject. I guess a blog post on this could be another option?

**Comment by iteles** [comment]
@LucyMac @msachi Quick tip: In the 'files changed' section, you can click on the little '+' at the beginning of the line to add inline comments to the code/markdown rather than having to spend time providing context for you comments here in the 'Conversation' tab ☺️

**Comment by alwinsol** [comment]
Closing this PR as have now created a new one in READMEs for a more polished version of this document

**Pull request closed without merging**
